oc_admin:
    resource: "@OCAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

oc_quest:
    resource: "@OCQuestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:   /login
    defaults:  { _controller: OCAdminBundle:Security:login }

login_check:
    path:   /login_check
    
logout:
    path:   /logout
    